=== francisjerin/mb-pde/MasterThesis/dynamicfacts/schema_detection.dtd
<!ELEMENT entry (entry*)>
<!ATTLIST entry args CDATA #REQUIRED>
<!ATTLIST entry className CDATA #REQUIRED>
<!ATTLIST entry methodName CDATA #REQUIRED>
<!ATTLIST entry calledByClass CDATA #REQUIRED>
<!ATTLIST entry calledByMethod CDATA  #REQUIRED>
<!ATTLIST entry calledByObject CDATA  #REQUIRED>
<!ATTLIST entry thisObject CDATA #REQUIRED>
<!ATTLIST entry nextCallInSubtree CDATA #REQUIRED>
<!ATTLIST entry nextCallInOrder CDATA #REQUIRED>
<!ATTLIST entry quantifier CDATA #REQUIRED>

=== francisjerin/mb-pde/MasterThesis/dynamicdefinitions_without_order/ajp_code.observer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entry SYSTEM "schema_detection.dtd">
<entry args="" className="concreteSubject" methodName="Constructor"
	thisObject="" calledByClass="" calledByMethod="" 
	nextCallInOrder="" calledByObject=""
	nextCallInSubtree="" quantifier="1">
	<entry nextCallInOrder="" calledByMethod="" nextCallInSubtree="" thisObject="object1" className="concreteObserver" calledByObject="" args="" calledByClass="" quantifier="3" methodName="Constructor">
		<entry nextCallInOrder="" calledByMethod=""
			nextCallInSubtree="" thisObject="object2"
			className="concreteObserver" calledByObject="" args="" calledByClass="" quantifier="1"
			methodName="Constructor"><!--this is another concrete observer-->
		</entry>
	</entry><entry nextCallInOrder="" calledByMethod=""
		nextCallInSubtree="" thisObject="object1"
		className="concreteObserver" calledByObject="" args="concreteSubject"
		calledByClass="" methodName="" quantifier="4">
	<entry nextCallInOrder="" calledByMethod=""
		nextCallInSubtree="" thisObject=""
		className="concreteSubject" calledByObject="" args="" calledByClass="concreteSubject" quantifier="2"
		methodName="">
		<entry nextCallInOrder="" calledByMethod=""
			nextCallInSubtree="" thisObject="object1"
			className="concreteObserver" calledByObject="" args="" calledByClass="concreteSubject" quantifier="3"
			methodName="">
			<entry nextCallInOrder="" calledByMethod=""
				nextCallInSubtree="" thisObject=""
				className="concreteSubject" calledByObject="object1" args="" calledByClass="concreteObserver"
				quantifier="3" methodName="">
				<entry nextCallInOrder=""  calledByMethod=""
					nextCallInSubtree="" thisObject="object2"
					className="concreteObserver" calledByObject="" args="" calledByClass="concreteSubject"
					quantifier="1" methodName="">
					<entry nextCallInOrder="" 
						calledByMethod="" nextCallInSubtree=""
						thisObject="" className="concreteSubject" calledByObject="object2" args=""
						calledByClass="concreteObserver" quantifier="1" methodName="">
					</entry>
				</entry>
			</entry>
		</entry>
	</entry>
</entry>
	
</entry>
